### ISSUE TITLE
Can't get it to run on mac or linux.

### ISSUE THREAD

**Issue by Promises** [lare96/asteria-3.0#21]
this is the log:

Jul 26, 2015 10:40:03 AM com.asteria.game.plugin.PluginHandler init
SEVERE: An error has occured while initializing the Bootstrap!
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at com.asteria.game.plugin.PluginHandler.init(PluginHandler.java:52)
    at com.asteria.ServerBuilder$$Lambda$16/1323165413.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: ./bin/plugin/Bootstrap
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at plugin.Bootstrap$1.visitFile(Bootstrap.groovy:46)
    at plugin.Bootstrap$1.visitFile(Bootstrap.groovy)
    at java.nio.file.Files.walkFileTree(Files.java:2670)
    at java.nio.file.Files.walkFileTree(Files.java:2742)
    at java_nio_file_Files$walkFileTree.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at plugin.Bootstrap.init(Bootstrap.groovy:38)
    at plugin.Bootstrap$init.callStatic(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:165)
    at plugin.Bootstrap.provide(Bootstrap.groovy:31)
    at plugin.Bootstrap.<init>(Bootstrap.groovy:20)
    ... 9 more

Jul 26, 2015 10:40:03 AM com.asteria.Server main
INFO: Asteria 3.0 is now online!

**Comment by ghost** [comment]
If lare remembered what I told him(because I fixed this) he would of applied the patch :)

**Comment by lare96** [comment]
"If lare remembered what I told him(because I fixed this) he would of applied the patch" Pretty sure I told you to create an issue...........................

**Comment by ghost** [comment]
I gave you the fix man...

**Comment by Promises** [comment]
Could you tell me the fix?

**Comment by lare96** [comment]
Artem, if you know the fix then say it. Saying you have it and not commenting what it is, is just counterproductive

**Comment by ghost** [comment]
Looks like lare haven't posted the fix that I've told him earlier. 

String formatted = file.path.replace("\", ".").substring(0, file.path.lastIndexOf(".")).replace("bin.", "").replace("..", "").replace("./bin/", "").replace("/", ".")

in the Bootstrap class.

**Comment by lare96** [comment]
https://github.com/lare96/asteria-3.0/pull/22
